### ISSUE TITLE
No timeout configuration for DNS resolver

### ISSUE THREAD

**Issue by AlexeyDemidov** [rubygarage/truemail#13]
There is no timeout configuration for DNS resolver when MX checks are done, so if there is a domain with bad DNS being checked then it could take up to 75 seconds before DNS timeouts which can be unacceptable, especially within web application context. There is also seems to be no rescue for DNS resolver timeouts.

**Comment by bestwebua** [comment]
Thank you, Alexey :+1: Fixed!
