### ISSUE TITLE
SMTP error interpretation 

### ISSUE THREAD

**Issue by AlexeyDemidov** [rubygarage/truemail#19]
Error code 550 followed by user|account doesn't  cover all possible error response which indicate that email doesn't exist. See an example of [SMTP error parsing for userunknown status](https://github.com/sisimai/rb-Sisimai/blob/027e0e027073df87658d7984e222473111773e22/lib/sisimai/reason/userunknown.rb#L19).

**Comment by bestwebua** [comment]
Thanks for example. But this option for cases when SMTP server does not return an exact answer that the email does not exist.
