### ISSUE TITLE
A DNS error causes MX lookup to break MX enumeration

### ISSUE THREAD

**Issue by AlexeyDemidov** [rubygarage/truemail#26]
In a situation when we have unresolvable primary MX record but healthy backup MX records

MX 0 unresolvable.example.com.
MX 10 healthy1.example.com.
MX 20 healthy2.example.com.

 validator won't be able to find backup records as a loop in `mx_records` method will stop on the first `Resolv::ResolvError`.

**Comment by bestwebua** [comment]
Thanks, Alexey! I think the point of this gem is in any way possible to validate email. So if this way has no strict following of current standards it's okay. For this case it's a chance to try to establish a connection with available mx hosts and receive info about user email existence. I will remove all mentions about strict compliance of RFC 5321 for MX validator in next release. Also it may be interesting feature for gem configurator, ability to use strict RFC following or not.
