### ISSUE TITLE
Multihomed MX records use only a single IP

### ISSUE THREAD

**Issue by AlexeyDemidov** [rubygarage/truemail#28]
When we have multi-homed MX record(s) which resolves into multiple A records   eg.
```
@ IN MX 0 mail.example.com.
mail.example.com. IN A 192.168.100.1
mail.example.com. IN A 192.168.100.2
```
Only a single IP address will be checked as `Resolv.getaddress` is used for MX hosts name resolution instead of `Resolv.getaddresses`.

**Comment by bestwebua** [comment]
Hi, Alexey! It make a sense, but what's wrong? In realization below we get array of mx records, and convert each mx record object to ip adress.

```ruby
def mx_records(domain)
  Resolv::DNS.new.getresources(domain, Resolv::DNS::Resource::IN::MX).map do |mx_record|
    Resolv.getaddress(mx_record.exchange.to_s)
  end
end
```

**Comment by AlexeyDemidov** [comment]
Each MX record contains a single hostname but this hostname can have multiple A records so it resolves into multiple IP addresses. When a single hostname resolves into multiple IPs  it is called multihomed host. In my example above you can see only one MX record but it resolves into multiple address. With this example current implementation using `getaddress` returns only one IP out of two (192.168.100.1 and 192.168.100.2) actually present in DNS for hostname `mail.example.com`. You need to use `getaddresses` to get an array of IP addresses returned for a single MX record.

**Comment by bestwebua** [comment]
Thanks for explanation, @AlexeyDemidov! I will fix it in next release :+1:

**Comment by bestwebua** [comment]
Fixed!
