### ISSUE TITLE
Question about server behind load balancer

### ISSUE THREAD

**Issue by majksner** [rubygarage/truemail#44]
Hi, first of all thanks for the gem!  It is really useful. I can't find where I can ask question except here.

I'm not sure how to perform SMTP validation when server is behind load balancer with internal IP only. 

`Truemail.host_audit` always fails because server doesn't have public IP and I can't configure one.

Any suggestions?

**Comment by bestwebua** [comment]
Hi, Nikola! You're welcome. What version of Truemail you have used? From ```0.1.8``` and higher I have used third party service for detect IP address instead ```Resolv.getaddress(Socket.gethostname)```, and it should work in any case. Could you provide some your error details, what ```Truemail.host_audit``` has returned? This feature is for quick host diagnostic only.

You can check it manually, just run this one in bash:
```
dig -x you_ip_address
```

**Comment by majksner** [comment]
Hi Vladislav,

I'm currently using `0.1.10` version in production environment.

`Truemail.host_audit` returns:
```ruby
<Truemail::Auditor:0x0000563a72defdc0 @result=#<struct Truemail::Auditor::Result warnings={:ptr=>"ptr record does not reference to current verifier domain"}>>
```

`curl ifconfig.co/json` returns:
```json
{"ip":"35.195.157.131","ip_decimal":600022403,"country":"United States","country_eu":false,"country_iso":"US","hostname":"131.157.195.35.bc.googleusercontent.com","latitude":47,"longitude":8}
```

Dig output:

```
$ dig -x 35.195.157.131

; <<>> DiG 9.11.3-1ubuntu1.7-Ubuntu <<>> -x 35.195.157.131
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49994
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;131.157.195.35.in-addr.arpa.	IN	PTR

;; ANSWER SECTION:
131.157.195.35.in-addr.arpa. 119 IN	PTR	131.157.195.35.bc.googleusercontent.com.

;; Query time: 4 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Wed Jun 05 07:27:02 UTC 2019
;; MSG SIZE  rcvd: 109
```

My Truemail config:

```ruby
Truemail.configure do |config|
  config.verifier_email = "verifier@airshaper.com"
end
```

I know my verifier domain doens't match PTR record of the instance that I use, Instance officially doesn't have public IP in Google Cloud Console, however when I run `curl ifconfig.co/json` I get public IP that could be an address of NAT gateway.

**Comment by AlexeyDemidov** [comment]
Hi Nikola,

Google Cloud instances are blocked from using outgoing SMTP connections (see their [documentation)](https://cloud.google.com/compute/docs/tutorials/sending-mail/) so it is impossible to use SMTP validation directly. You can only use `:regex` and `:mx` type validation.

**Comment by majksner** [comment]
Thank you for you answer. Is it possible to use other ports, I guess most major providers supports 587 and 465? If so I can send pull request to add SMTP port configurable?

**Comment by AlexeyDemidov** [comment]
No, port 587 is used for client mail submission and usually requires authentication and port 465 is non-standard port for encrypted SMTP.  Most major providers (eg. gmail, outlook, yahoo) don't support those ports on their MX servers.

**Comment by majksner** [comment]
Ok, thank you very much for the explanation!

**Comment by bestwebua** [comment]
Hello, @majksner! Sorry for delay with answer. As @AlexeyDemidov mentioned, for your case you can't use smtp validation. But as alternate way you can use truemail gem on a different host with white public IP and delegate email validation to this service.

Most major providers supports 587 and 465, but what would if you can try to connect? For instance, gmail case:

```bash
nc alt3.gmail-smtp-in.l.google.com 587 # nothing
nc alt3.gmail-smtp-in.l.google.com 465 # nothing
```

**Comment by majksner** [comment]
@bestwebua Can you elaborate more on "use truemail gem on a different host with white public IP and delegate email validation to this service."

**Comment by majksner** [comment]
@bestwebua You mean to run truemail as a microservice on  another provider and run email validations though an API?

**Comment by majksner** [comment]
Got it 👌

**Comment by bestwebua** [comment]
@majksner, yes! I plane to realize example app for this case when I will have free time. Cheers!

**Comment by bestwebua** [comment]
Hello, @majksner! Now you can use ***Truemail*** as [independent microservice](https://github.com/truemail-rb/truemail-rack). Also this app now available as [docker image](https://hub.docker.com/r/truemail/truemail-rack) :whale: Cheers!

**Comment by majksner** [comment]
Thank you so much for letting me know.

**Comment by bestwebua** [comment]
> Thank you so much for letting me know.

You're welcome, @majksner!

**Comment by bestwebua** [comment]
@majksner Also the first version of Truemail [web API client library](https://github.com/truemail-rb/truemail-ruby-client) for Ruby was released just now 🚀
