### ISSUE TITLE
Feature request: opt out of SMTP validation

### ISSUE THREAD

**Issue by giovannibonetti** [rubygarage/truemail#48]
### New Issue Checklist

- [x] I have updated truemail to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/rubygarage/truemail/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://github.com/rubygarage/truemail/blob/master/README.md)
- [x] I have searched for [existing GitHub issues](https://github.com/rubygarage/truemail/issues)

### Feature request

Hi! I really like this library, but I'm wondering if there is any drawback to using the final SMTP validation. Is it possible that the my email domain (from `verifier_email`) might get an increase in its spam score since the verification sends a [real SMTP request](https://github.com/rubygarage/truemail/blob/master/lib/truemail/validate/smtp/request.rb) for each verified email address on behalf of it?

What do you think about making SMTP validation optional and also disabling it by default if `verifier_email` is not set?

**Comment by bestwebua** [comment]
Hello. @giovannibonetti! Thanks for your feedback. I will add default validation as configurable option in next release. Also you can run validation with param:

```ruby
Truemail.validate('email', with: :mx)
```
or configure not smtp validation for domain(s) that reject smtp validation
```ruby
Truemail.configure do |config|
  config.validation_type_for = { 'somedomain.com' => :mx }
end
```

**Comment by giovannibonetti** [comment]
Thanks for the quick response! 😀

**Comment by bestwebua** [comment]
> Thanks for the quick response! grinning

@giovannibonetti, this feature is available in Truemail 1.1.0. Cheers!

**Comment by giovannibonetti** [comment]
Thanks, @bestwebua! 😀 

By the way, do you think it makes sense to make `verifier_email` optional in case of `mx` validation?
```ruby
require 'truemail'

Truemail.configure do |config|
  config.default_validation_type = :mx
end
```

I tried to use it like that but it still requires a verifier_email.
```
/usr/local/bundle/gems/truemail-1.1.0/lib/truemail.rb:45:in `raise_unless': verifier_email is required parameter (Truemail::ConfigurationError)
from /usr/local/bundle/gems/truemail-1.1.0/lib/truemail.rb:15:in `configuration'
from /usr/local/bundle/gems/truemail-1.1.0/lib/truemail.rb:21:in `configure'
```

I know I can just set a dummy value to `config.verifier_email`, but maybe it would make sense to delay the presence validation until it is actually required, which is at the moment a `smtp` validation is requested.

**Comment by bestwebua** [comment]
Hi, @giovannibonetti! Thanks for your feedback. But what will happen if ```verifier_email``` will be an optional parameter and you will run ```Truemail.validate('email@email.com', with: :smtp)``` without configured ```verifier_email```? Tuemail will crash. Therefore I think that ```verifier_email``` should be required parameter in any case.

**Comment by giovannibonetti** [comment]
Ok, understood. Thanks for your time!

**Comment by bestwebua** [comment]
Your'e welcome!
