### ISSUE TITLE
Allow Punycode In Domain

### ISSUE THREAD

**Issue by kivlor** [rubygarage/truemail#61]
### New Issue Checklist

- [x] I have updated truemail to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/rubygarage/truemail/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://github.com/rubygarage/truemail/blob/master/README.md)
- [x] I have searched for [existing GitHub issues](https://github.com/rubygarage/truemail/issues)

### Issue Description

When loading a domain converted to punycode (e.g.: [xn--ls8h.la](http://xn--ls8h.la)) I get `Truemail::ArgumentError (["xn--ls8h.la"] is not a valid blacklisted_domains=`

##### Complete output when running truemail, including the stack trace and command used

<details>
  <pre>
irb(main):002:0> Truemail.configuration.blacklisted_domains = ['xn--ls8h.la']
Traceback (most recent call last):
        1: from (irb):2
Truemail::ArgumentError (["xn--ls8h.la"] is not a valid blacklisted_domains=)
  </pre>
</details>

**Comment by bestwebua** [comment]
Hi, @kivlor! Thanks for your suggestion and PR. Do you need punycode domain supporting for `blacklisted_domains` only?

**Comment by kivlor** [comment]
@bestwebua currently we've only added punycode domains to the `blacklisted_domains` but I could see others using them in `waitlisted_domains` as well

**Comment by bestwebua** [comment]
@kivlor, I don't think so that allowing punycodes is a good idea. Actually it's a good point for punycode phishing. I prefer use UTF8 over punycode for email addresses, good thoughts about: https://rant.gulbrandsen.priv.no/eai/utf8-punycode

I will add `REGEX_DOMAIN` configurable option in next release, so it will cover case with national coding.

**Comment by kivlor** [comment]
@bestwebua I appreciate the feedback. I suggested converting to punycode in hopes of making the regex simpler. After reading through [https://www.regular-expressions.info/unicode.html](https://www.regular-expressions.info/unicode.html), maybe supporting unicode isn't a big issue 🤔 

Anyway, I'll keep an eye out for the next release 😄

**Comment by bestwebua** [comment]
You're welcome, @kivlor!

**Comment by bestwebua** [comment]
Hello, @kivlor! Meet new :rocket: Truemail release with EAI supporting: #66 Happy holidays! :christmas_tree: :santa: :gift: :snowman_with_snow:

**Comment by kivlor** [comment]
Great work @bestwebua! Happy holidays 🎅
