### ISSUE TITLE
unable to use truemail for ruby 2.3.1.

### ISSUE THREAD

**Issue by PrabhuPuredla95** [rubygarage/truemail#73]
I am trying to use truemail in the project with ruby version 2.3.1, 
error: Bundler could not find compatible versions for gem "ruby":
  In Gemfile:
    ruby
    truemail (= 1.0.0) was resolved to 1.0.0, which depends on
      ruby (>= 2.5.0)
Is there any version of truemail that supports ruby 2.3.1?

**Comment by bestwebua** [comment]
Hi, @PrabhuPuredla95! Thanks for your question. It happens because current version of truemail depends on ruby >=2.5. Maybe I will add supporting ruby 2.3 on next releases. Cheers!

**Comment by amenon** [comment]
@bestwebua any updates on supporting ruby 2.3? I am happy to help in any way.

**Comment by vizcay** [comment]
Hi!

The hardcoded ruby version to 2.5 is for some specific reason?

I have a bunch of rails apps running with ruby 2.4 that could benefit from using this gem and I was considering forking just to drop the version and see if it works.
