### ISSUE TITLE
default REGEX_DOMAIN incorrectly limits top level domain to 7 characters max

### ISSUE THREAD

**Issue by AlexeyDemidov** [rubygarage/truemail#8]
default REGEX_DOMAIN restricts top level domain part to only 7 characters, which will incorrectly reject as invalid 512 out of 1532 currently existing TLDs as the longest one is 24 characters long. Please see http://data.iana.org/TLD/tlds-alpha-by-domain.txt for the full list of currently exiting TLD. Proper limit should be 63 characters.

**Comment by bestwebua** [comment]
:+1: Fixed!
