### ISSUE TITLE
Communicate withPython 

### ISSUE THREAD

**Issue by majid1f** [rubygarage/truemail#86]
How we can communicate truemail with in python scripts (or other lanaguge like PHP) ?

**Comment by bestwebua** [comment]
Hi, @majid1f You can use Truemail as independent microservice. For tooday you can use one of the **truemail-rb** solutions:
1. [truemail server](https://github.com/truemail-rb/truemail-rack) - lightweight rack based web API wrapper for Truemail
2. [truemail-rack-docker](https://github.com/truemail-rb/truemail-rack-docker-image) - lightweight rack based web API [dockerized image](https://hub.docker.com/r/truemail/truemail-rack) 🐳 of Truemail server

Also look at https://github.com/truemail-rb
I believe that I will finish Truemail Python client till the end of the next month. Cheers 🍺
