### ISSUE TITLE
Domain names are case insensitive 

### ISSUE THREAD

**Issue by AlexeyDemidov** [rubygarage/truemail#9]
Domain names are case insensitive, e.g. example.com, EXAMPLE.COM and examPLE.Com should all be treated as the same domain, but this code currently allows only lowercase domain names and rejects uppercase or mixed-case as invalid.

**Comment by bestwebua** [comment]
Hello Alexey! Indeed it is true, but properly configured server never should return 'DoMain.cOm' as HELO request argument.

**Comment by AlexeyDemidov** [comment]
This is not true - there is nothing in the current standards preventing usage of uppercase or mixed-case domains (See RFC 4343). There is common usage of all uppercase emails like JOHN.DOE@GMAIL.COM (especially in Windows environment as they historically defaulted to uppercase domain names) or mixed case emails like John.Doe@GMail.com. Those emails are valid and are accepted and delivered by standard complaint mail software without problem.  But `Truemail.validate('John.Doe@GMail.com')` and `Truemail.validate('JOHN.DOE@GMAIL.COM')` both return error `email does not match the regular expression`.

**Comment by bestwebua** [comment]
Thank you, Alexey :+1: It will be fixed in next version
