### ISSUE TITLE
Better handling nil or non-string values?

### ISSUE THREAD

**Issue by duckworth** [rubygarage/truemail#93]
### New Issue Checklist

- [ x] I have updated truemail to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/rubygarage/truemail/blob/master/CONTRIBUTING.md)
- [x ] I have read the [documentation](https://github.com/rubygarage/truemail/blob/master/README.md)
- [x ] I have searched for [existing GitHub issues](https://github.com/rubygarage/truemail/issues)

### Issue Description

Calling Truemail.validate() or Truemail.valid?() with nil or non String values throws errors.
##### Complete output when running truemail, including the stack trace and command used

<details>
  <pre> Truemail.valid?(nil)
NoMethodError: undefined method `[]' for nil:NilClass
from .../gems/ruby-2.6.5/gems/truemail-1.9.1/lib/truemail/validator.rb:42:in `select_validation_type'</pre>
</details>

Took me a while to track down why my Validator was failing and seems somewhat unexpected result.

**Comment by bestwebua** [comment]
Hi, @duckworth! Thanks for your feedback. Follows [the docs](https://truemail-rb.org/truemail-gem/#/quick-start?id=dsl-example) it's an expected behaviour for these cases. But I will add type-check handler in next release. Cheers!
